# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToolsDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 use_frameworks!

  # Pods for ToolsDemo

  target 'ToolsDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToolsDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod ‘Tools’ , :path => ‘../’

end
